# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUnoJqC2MM6qKsAvVIip8OdJyQGMVttM
"""

import pandas as pd

df = pd.read_csv('actions.csv')

df.head()

print(df.groupby('date').size().reset_index().sort_values(by=0))  # Последнее значение - искомое

df.info()

df_filtered = df[df['date'].str.contains('.03.2023')]
print(df_filtered.ip.unique().size)  # Ответ

# df_filtered

cnt = 0
for s in df_filtered['action']:
    cnt += str(s).count('click')

print(cnt)  # Ответ
